# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b8b91a0ba65596469cf9d88b11cb3772"
name = "Cataloger Internal"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
